var myInsertion = {  UN  : 1,   AP  : 2,   0  : 3,   BL  : 4,   RL  : 5,   RM  : 6,   PC  : 7,   FL  : 8,   CX  : 9,   CN  : 10,   PT  : 11,   L  : 12,   GL  : 13,   MT  : 14,   KG  : 15,   P  : 16,   TB  : 17,   FR  : 18,   CP  : 19,   H  : 20,   PR  : 21,   DZ  : 22}
//var myInsertion = { APS : 1,  o : 2,  MATERIAL_GRAFICO : 3,  MATERIAL_DE_HIGIENE : 4,  PRODUTOS_ALIMENTICIOS : 5,  MATERIAL_DE_EXPEDIENTE : 6,  IMPRESSOES : 7,  EVENTOS : 8,  LANCHE_DIRETORIA : 9,  MATERIAL_DE_DIVULGACAO : 10,  MANUTENCOES : 11,  MANUTENCAO_DE_VEICULOS : 12,  PRODUTO_DESCARTAVEL : 13,  INFORMATICA : 14,  MATERIAL_MEDICINA_PREVENTIVA : 15,  IMOBILIZADO : 16,  CLINICAS : 17,  MATERIAL_DE_COZINHA : 18,  HOMENAGENS_E_CONDOLENCIAS : 19,  VIAGENS_PASSAGENS_HOSPEDAGEM : 20,  SERVICO : 21,  DESPESAS_COM_TELEFONE : 22,  BISCOITOS_E_ACUCAR_RECEPCAO : 23,  AGUA_E_ESGOTO : 24,  UNIFORMES : 25,  PRODUTO_DE_LIMPEZA : 26,  CONFRATERNIZACOES : 27,  CURSOS_E_TREINAMENTO_FUNC : 28,  SEGURO_PREDIO : 29,  ESTOQUE_FARMACIA : 30,  PUBLICIDADE_E_PROPAGANDA : 31,  PATROCINIOS : 32,  PROJETOS_RS : 33,  ENERGIA : 34,  LICENCAS : 35,  MATERIAL_ELETRECO : 36,  CURSOS_COOPERADOS : 37,  UTENSILIOS : 38,  ALVARA_IPTU_IMPOSTOS_ISS : 39,  IMOVEIS_EM_CONSTRUCAO : 40,  LOCACAO_DE_IMOVEL : 41,  COMISSAO_VENDAS_PLANOS : 42,  MEDICAMENTOS : 43,  BENEFICIOS_FUNCIONARIOS : 44,  VIAGENS_HOSP_REFEICAO : 45,  MAQUINAS_DE_CAFE : 46,  PLANEJAMENTO_ESTRATEGICO : 47,  Produtos_Quimicos : 48,  ONCOLOGICO : 49};
console.log(myInsertion);
for (var insertion in myInsertion){
    var data = {
        id: myInsertion[insertion],
    }
    console.log(data)
    firebase.database().ref('/unidade_medida/ '+insertion).set(data);
}